package com.example.mooddiary.util

object L {

    val languages: List<Pair<String, String>> = listOf(
        "zh" to "中文",
        "en" to "English",
        "ko" to "한국어",
        "ja" to "日本語",
        "es" to "Español"
    )

    fun t(key: String, lang: String): String =
        dict[lang]?.get(key) ?: dict["zh"]?.get(key) ?: key

    private val dict: Map<String, Map<String, String>> = mapOf(

        "zh" to mapOf(
            "today_prefix" to "今天 · ",
            "not_recorded_today" to "还没记录今天",
            "tap_to_record" to "点这里记录此刻的心情",
            "streak_great" to "你好棒！已连续记录 %d 天啦",
            "streak_none" to "今天还没开始记录呢",
            "history" to "历史记录",
            "tab_home" to "主页",
            "tab_diary" to "日记",
            "diary_title" to "我的日记",
            "diary_new" to "写日记",
            "diary_edit" to "编辑日记",
            "diary_hint" to "今天发生了什么？",
            "diary_empty" to "还没有日记，写下第一篇吧 ✨",
            "diary_count" to "共 %d 篇",
            "diary_recent7" to "近 7 天 %d 篇",
            "diary_delete_confirm" to "确定删除这篇日记吗？",
            "total_count" to "共 %d 条",
            "empty_hint" to "还没有记录，点右下角 ＋ 开始",
            "record_mood" to "记录个心情吧",
            "edit_record" to "编辑记录",
            "date_label" to "日期",
            "today" to "今天",
            "mood_prompt" to "啥心情呢",
            "intensity_label" to "程度",
            "note_hint" to "发生了什么？（可选）",
            "backfill_hint" to "将在 %s 补录一条记录",
            "save" to "保存",
            "cancel" to "取消",
            "stats_title" to "情绪统计",
            "stats_month_count" to "本月记录 %d 天",
            "stats_empty" to "本月还没有记录呢 🌱",
            "close" to "关闭",
            "settings" to "设置",
            "ios_style" to "iOS 27 玻璃风格",
            "ios_current" to "当前：iOS 27 玻璃风",
            "material_current" to "当前：经典 Material 风",
            "export_csv" to "导出数据（CSV）",
            "export_desc" to "共 %d 条记录，可发到微信/抖音",
            "clear_all" to "清空所有数据",
            "clear_desc" to "不可恢复，请谨慎操作",
            "about" to "关于",
            "version" to "每日情绪账本 v 1.1.0-alpha01",
            "about_desc" to "记录每一天，你的内心助手",
            "author" to "本软件由魏文彬开发  " +
                    "Copyright © 2026 Cmpss. All Rights Reserved.",
            "clear_confirm" to "确定清空所有数据？",
            "clear_confirm_desc" to "将永久删除全部 %d 条记录，不可恢复。",
            "clear_yes" to "我真的确定清空",
            "clear_no" to "等等！我再想想",
            "menu_stats" to "情绪统计",
            "menu_card_style" to "卡片样式",
            "menu_backfill" to "补录历史",
            "menu_settings" to "设置",
            "menu_more" to "更多",
            "share_title" to "分享心情",
            "save_album" to "保存相册",
            "share" to "分享",
            "saved_to_album" to "已保存到相册",
            "save_failed" to "保存失败",
            "share_to" to "分享到",
            "card_style_title" to "卡片样式",
            "section_appearance" to "卡片外观",
            "label_background" to "背景",
            "bg_glass" to "玻璃",
            "bg_plain" to "纯色",
            "bg_gradient" to "渐变",
            "bg_photo" to "照片",
            "select_photo" to "选择自定义照片",
            "change_photo" to "更换照片",
            "photo_selected" to "已选择 · 点击更换",
            "clear_photo" to "清除",
            "show_emoji" to "显示 emoji",
            "show_date" to "显示日期",
            "show_stars" to "显示星星",
            "label_radius" to "圆角",
            "section_share_card" to "分享卡片",
            "use_custom_photo" to "使用自定义照片作为背景",
            "label_template" to "模板",
            "watermark" to "显示底部水印",
            "done" to "完成",
            "language" to "语言",
            "mood_happy" to "开心",
            "mood_calm" to "平静",
            "mood_sad" to "难过",
            "mood_angry" to "生气",
            "mood_anxious" to "焦虑",
            "custom_toggle" to "自定义图标和名称",
            "custom_toggle_collapse" to "收起自定义",
            "custom_scope_hint" to "保存后应用到所有「%s」记录",
            "custom_icon_label" to "图标",
            "custom_name_label" to "名称",
            "custom_preview" to "预览",
            "save_global" to "保存到全局",
            "clear" to "清除",
            "watermark_text" to "— 每日情绪账本 —",
            "watermark_national" to "— 每日情绪账本 · 国庆限定 —",
            "national_title" to "国庆快乐",
            "tpl_national" to "国庆",
            "tpl_classic" to "经典",
            "tpl_minimal" to "简约",
            "tpl_paper" to "杂志",
            "tpl_dark" to "暗夜",
            "tpl_note" to "便签",
            "custom_mood_new" to "新建情绪",
            "custom_mood_edit" to "编辑情绪",
            "custom_mood_delete" to "删除情绪",
            "custom_mood_emoji" to "图标",
            "custom_mood_label" to "名称",
            "custom_mood_add" to "添加",
            "custom_mood_empty" to "还没有自定义情绪",
            "custom_mood_hint" to "输入 emoji 和名称，创建一个新情绪",
            "custom_mood_delete_confirm" to "确定删除这个情绪？",
            "custom_mood_delete_desc" to "已记录的条目不会丢失，仍会显示",
            "delete" to "删除",
            "confirm" to "确定"
        ),

        "en" to mapOf(
            "today_prefix" to "Today · ",
            "not_recorded_today" to "Not recorded yet",
            "tap_to_record" to "Tap to record how you feel",
            "streak_great" to "Great! %d-day streak",
            "streak_none" to "No entry yet today",
            "history" to "History",
            "tab_home" to "Home",
            "tab_diary" to "Diary",
            "diary_title" to "My Diary",
            "diary_new" to "New entry",
            "diary_edit" to "Edit entry",
            "diary_hint" to "What happened today?",
            "diary_empty" to "No entries yet — write your first one ✨",
            "diary_count" to "%d entries",
            "diary_recent7" to "%d in the last 7 days",
            "diary_delete_confirm" to "Delete this entry?",
            "total_count" to "%d entries",
            "empty_hint" to "No entries yet. Tap + to start",
            "record_mood" to "Record mood",
            "edit_record" to "Edit entry",
            "date_label" to "Date",
            "today" to "Today",
            "mood_prompt" to "How are you?",
            "intensity_label" to "Intensity",
            "note_hint" to "What happened? (optional)",
            "backfill_hint" to "Will backfill on %s",
            "save" to "Save",
            "cancel" to "Cancel",
            "stats_title" to "Mood Stats",
            "stats_month_count" to "%d days this month",
            "stats_empty" to "No records this month 🌱",
            "close" to "Close",
            "settings" to "Settings",
            "ios_style" to "iOS 27 Glass Style",
            "ios_current" to "Current: iOS 27 Glass",
            "material_current" to "Current: Classic Material",
            "export_csv" to "Export Data (CSV)",
            "export_desc" to "%d entries, share via WeChat/TikTok",
            "clear_all" to "Clear All Data",
            "clear_desc" to "This cannot be undone",
            "about" to "About",
            "version" to "Mood Diary v 1.1.0-alpha01",
            "about_desc" to "Record every day, your inner assistant.",
            "author" to "Developed by Wenbin Wei  " +
                    "Copyright © 2026 Cmpss. All Rights Reserved.",
            "clear_confirm" to "Clear all data?",
            "clear_confirm_desc" to "Will permanently delete all %d entries.",
            "clear_yes" to "Yes, clear it",
            "clear_no" to "Wait, let me think",
            "menu_stats" to "Mood Stats",
            "menu_card_style" to "Card Style",
            "menu_backfill" to "Backfill",
            "menu_settings" to "Settings",
            "menu_more" to "More",
            "share_title" to "Share Mood",
            "save_album" to "Save to Album",
            "share" to "Share",
            "saved_to_album" to "Saved to album",
            "save_failed" to "Save failed",
            "share_to" to "Share to",
            "card_style_title" to "Card Style",
            "section_appearance" to "Appearance",
            "label_background" to "Background",
            "bg_glass" to "Glass",
            "bg_plain" to "Plain",
            "bg_gradient" to "Gradient",
            "bg_photo" to "Photo",
            "select_photo" to "Select custom photo",
            "change_photo" to "Change photo",
            "photo_selected" to "Selected · tap to change",
            "clear_photo" to "Clear",
            "show_emoji" to "Show emoji",
            "show_date" to "Show date",
            "show_stars" to "Show stars",
            "label_radius" to "Radius",
            "section_share_card" to "Share Card",
            "use_custom_photo" to "Use custom photo as background",
            "label_template" to "Template",
            "watermark" to "Show watermark",
            "done" to "Done",
            "language" to "Language",
            "mood_happy" to "Happy",
            "mood_calm" to "Calm",
            "mood_sad" to "Sad",
            "mood_angry" to "Angry",
            "mood_anxious" to "Anxious",
            "custom_toggle" to "Custom icon & name",
            "custom_toggle_collapse" to "Collapse",
            "custom_scope_hint" to "Applies to all \"%s\" records",
            "custom_icon_label" to "Icon",
            "custom_name_label" to "Name",
            "custom_preview" to "Preview",
            "save_global" to "Save globally",
            "clear" to "Clear",
            "watermark_text" to "— Mood Diary —",
            "watermark_national" to "— Mood Diary · National Day —",
            "national_title" to "Happy National Day",
            "tpl_national" to "National",
            "tpl_classic" to "Classic",
            "tpl_minimal" to "Minimal",
            "tpl_paper" to "Paper",
            "tpl_dark" to "Dark",
            "tpl_note" to "Note",
            "custom_mood_new" to "New mood",
            "custom_mood_edit" to "Edit mood",
            "custom_mood_delete" to "Delete mood",
            "custom_mood_emoji" to "Icon",
            "custom_mood_label" to "Name",
            "custom_mood_add" to "Add",
            "custom_mood_empty" to "No custom moods yet",
            "custom_mood_hint" to "Enter emoji & name to create a new mood",
            "custom_mood_delete_confirm" to "Delete this mood?",
            "custom_mood_delete_desc" to "Existing entries remain visible",
            "delete" to "Delete",
            "confirm" to "Confirm"
        ),

        "ko" to mapOf(
            "today_prefix" to "오늘 · ",
            "not_recorded_today" to "오늘 기록이 없어요",
            "tap_to_record" to "지금의 기분을 기록하세요",
            "streak_great" to "대단해요! %d일 연속 기록",
            "streak_none" to "오늘 아직 기록이 없어요",
            "history" to "기록",
            "tab_home" to "홈",
            "tab_diary" to "일기",
            "diary_title" to "나의 일기",
            "diary_new" to "일기 쓰기",
            "diary_edit" to "일기 편집",
            "diary_hint" to "오늘 무슨 일이 있었나요?",
            "diary_empty" to "아직 일기가 없어요. 첫 일기를 써 보세요 ✨",
            "diary_count" to "%d편",
            "diary_recent7" to "최근 7일 %d편",
            "diary_delete_confirm" to "이 일기를 삭제할까요?",
            "total_count" to "%d개",
            "empty_hint" to "기록이 없어요. ＋를 눌러 시작하세요",
            "record_mood" to "기분 기록",
            "edit_record" to "기록 수정",
            "date_label" to "날짜",
            "today" to "오늘",
            "mood_prompt" to "기분이 어때요?",
            "intensity_label" to "강도",
            "note_hint" to "무슨 일이 있었나요? (선택)",
            "backfill_hint" to "%s에 소급 기록합니다",
            "save" to "저장",
            "cancel" to "취소",
            "stats_title" to "기분 통계",
            "stats_month_count" to "이번 달 %d일 기록",
            "stats_empty" to "이번 달 기록이 없어요 🌱",
            "close" to "닫기",
            "settings" to "설정",
            "ios_style" to "iOS 27 글래스 스타일",
            "ios_current" to "현재: iOS 27 글래스",
            "material_current" to "현재: 클래식 Material",
            "export_csv" to "데이터 내보내기 (CSV)",
            "export_desc" to "%d개 기록, WeChat/틱톡으로 공유",
            "clear_all" to "모든 데이터 삭제",
            "clear_desc" to "복구할 수 없습니다",
            "about" to "정보",
            "version" to "무드 다이어리 v 1.1.0-alpha01",
            "about_desc" to "매일을 기록하다, 당신의 마음 비서",
            "author" to "Wenbin Wei 제작  " +
                    "Copyright © 2026 Cmpss. All Rights Reserved.",
            "clear_confirm" to "모든 데이터를 삭제하시겠어요?",
            "clear_confirm_desc" to "%d개의 모든 기록이 영구 삭제됩니다.",
            "clear_yes" to "네, 삭제합니다",
            "clear_no" to "잠깐, 다시 생각할게요",
            "menu_stats" to "기분 통계",
            "menu_card_style" to "카드 스타일",
            "menu_backfill" to "소급 기록",
            "menu_settings" to "설정",
            "menu_more" to "더보기",
            "share_title" to "기분 공유",
            "save_album" to "앨범에 저장",
            "share" to "공유",
            "saved_to_album" to "앨범에 저장됨",
            "save_failed" to "저장 실패",
            "share_to" to "공유 대상",
            "card_style_title" to "카드 스타일",
            "section_appearance" to "카드 외관",
            "label_background" to "배경",
            "bg_glass" to "글래스",
            "bg_plain" to "단색",
            "bg_gradient" to "그라데이션",
            "bg_photo" to "사진",
            "select_photo" to "사용자 사진 선택",
            "change_photo" to "사진 변경",
            "photo_selected" to "선택됨 · 탭하여 변경",
            "clear_photo" to "지우기",
            "show_emoji" to "이모지 표시",
            "show_date" to "날짜 표시",
            "show_stars" to "별점 표시",
            "label_radius" to "모서리",
            "section_share_card" to "공유 카드",
            "use_custom_photo" to "사용자 사진을 배경으로",
            "label_template" to "템플릿",
            "watermark" to "워터마크 표시",
            "done" to "완료",
            "language" to "언어",
            "mood_happy" to "행복",
            "mood_calm" to "평온",
            "mood_sad" to "슬픔",
            "mood_angry" to "화남",
            "mood_anxious" to "불안",
            "custom_toggle" to "아이콘 및 이름 사용자 지정",
            "custom_toggle_collapse" to "접기",
            "custom_scope_hint" to "모든 \"%s\" 기록에 적용됩니다",
            "custom_icon_label" to "아이콘",
            "custom_name_label" to "이름",
            "custom_preview" to "미리보기",
            "save_global" to "전체 저장",
            "clear" to "지우기",
            "watermark_text" to "— 무드 다이어리 —",
            "watermark_national" to "— 무드 다이어리 · 국경일 —",
            "national_title" to "국경일 축하",
            "tpl_national" to "국경일",
            "tpl_classic" to "클래식",
            "tpl_minimal" to "미니멀",
            "tpl_paper" to "잡지",
            "tpl_dark" to "다크",
            "tpl_note" to "메모",
            "custom_mood_new" to "새 감정",
            "custom_mood_edit" to "감정 편집",
            "custom_mood_delete" to "감정 삭제",
            "custom_mood_emoji" to "아이콘",
            "custom_mood_label" to "이름",
            "custom_mood_add" to "추가",
            "custom_mood_empty" to "사용자 감정 없음",
            "custom_mood_hint" to "이모지와 이름을 입력하세요",
            "custom_mood_delete_confirm" to "이 감정을 삭제하시겠어요?",
            "custom_mood_delete_desc" to "기존 기록은 계속 표시됩니다",
            "delete" to "삭제",
            "confirm" to "확인"
        ),

        "ja" to mapOf(
            "today_prefix" to "今日 · ",
            "not_recorded_today" to "今日の記録はまだありません",
            "tap_to_record" to "タップして今の気持ちを記録",
            "streak_great" to "すごい！%d日連続記録中",
            "streak_none" to "今日はまだ記録がありません",
            "history" to "履歴",
            "tab_home" to "ホーム",
            "tab_diary" to "日記",
            "diary_title" to "私の日記",
            "diary_new" to "日記を書く",
            "diary_edit" to "日記を編集",
            "diary_hint" to "今日は何がありましたか？",
            "diary_empty" to "まだ日記がありません。最初の一篇を書きましょう ✨",
            "diary_count" to "%d件",
            "diary_recent7" to "直近7日 %d件",
            "diary_delete_confirm" to "この日記を削除しますか？",
            "total_count" to "%d件",
            "empty_hint" to "記録がありません。＋で開始",
            "record_mood" to "気持ちを記録",
            "edit_record" to "記録を編集",
            "date_label" to "日付",
            "today" to "今日",
            "mood_prompt" to "気分はどうですか？",
            "intensity_label" to "強度",
            "note_hint" to "何がありましたか？（任意）",
            "backfill_hint" to "%sに遡って記録します",
            "save" to "保存",
            "cancel" to "キャンセル",
            "stats_title" to "気分統計",
            "stats_month_count" to "今月%d日の記録",
            "stats_empty" to "今月の記録はありません 🌱",
            "close" to "閉じる",
            "settings" to "設定",
            "ios_style" to "iOS 27 グラススタイル",
            "ios_current" to "現在：iOS 27 グラス",
            "material_current" to "現在：クラシック Material",
            "export_csv" to "データ書き出し（CSV）",
            "export_desc" to "%d件の記録、WeChat/TikTokで共有",
            "clear_all" to "すべてのデータを削除",
            "clear_desc" to "復元できません",
            "about" to "について",
            "version" to "ムードダイアリー v 1.1.0-alpha01",
            "about_desc" to "毎日を記録する、あなたの心のアシスタント",
            "author" to "Wenbin Wei 開発  " +
                    "Copyright © 2026 Cmpss. All Rights Reserved.",
            "clear_confirm" to "すべてのデータを削除しますか？",
            "clear_confirm_desc" to "%d件の記録が永久に削除されます。",
            "clear_yes" to "はい、削除します",
            "clear_no" to "ちょっと待って",
            "menu_stats" to "気分統計",
            "menu_card_style" to "カードスタイル",
            "menu_backfill" to "遡って記録",
            "menu_settings" to "設定",
            "menu_more" to "その他",
            "share_title" to "気持ちを共有",
            "save_album" to "アルバムに保存",
            "share" to "共有",
            "saved_to_album" to "アルバムに保存しました",
            "save_failed" to "保存に失敗しました",
            "share_to" to "共有先",
            "card_style_title" to "カードスタイル",
            "section_appearance" to "カードの外観",
            "label_background" to "背景",
            "bg_glass" to "グラス",
            "bg_plain" to "単色",
            "bg_gradient" to "グラデーション",
            "bg_photo" to "写真",
            "select_photo" to "カスタム写真を選択",
            "change_photo" to "写真を変更",
            "photo_selected" to "選択済み · タップで変更",
            "clear_photo" to "クリア",
            "show_emoji" to "絵文字を表示",
            "show_date" to "日付を表示",
            "show_stars" to "星を表示",
            "label_radius" to "角丸",
            "section_share_card" to "共有カード",
            "use_custom_photo" to "カスタム写真を背景に",
            "label_template" to "テンプレート",
            "watermark" to "ウォーターマークを表示",
            "done" to "完了",
            "language" to "言語",
            "mood_happy" to "嬉しい",
            "mood_calm" to "穏やか",
            "mood_sad" to "悲しい",
            "mood_angry" to "怒り",
            "mood_anxious" to "不安",
            "custom_toggle" to "アイコンと名前をカスタマイズ",
            "custom_toggle_collapse" to "折りたたむ",
            "custom_scope_hint" to "すべての「%s」記録に適用されます",
            "custom_icon_label" to "アイコン",
            "custom_name_label" to "名前",
            "custom_preview" to "プレビュー",
            "save_global" to "全体に保存",
            "clear" to "クリア",
            "watermark_text" to "— ムードダイアリー —",
            "watermark_national" to "— ムードダイアリー · 国慶節 —",
            "national_title" to "国慶節おめでとう",
            "tpl_national" to "国慶節",
            "tpl_classic" to "クラシック",
            "tpl_minimal" to "ミニマル",
            "tpl_paper" to "マガジン",
            "tpl_dark" to "ダーク",
            "tpl_note" to "メモ",
            "custom_mood_new" to "新しい気分",
            "custom_mood_edit" to "気分を編集",
            "custom_mood_delete" to "気分を削除",
            "custom_mood_emoji" to "アイコン",
            "custom_mood_label" to "名前",
            "custom_mood_add" to "追加",
            "custom_mood_empty" to "カスタム気分がありません",
            "custom_mood_hint" to "絵文字と名前を入力してください",
            "custom_mood_delete_confirm" to "この気分を削除しますか？",
            "custom_mood_delete_desc" to "既存の記録は表示されたままです",
            "delete" to "削除",
            "confirm" to "確認"
        ),

        "es" to mapOf(
            "today_prefix" to "Hoy · ",
            "not_recorded_today" to "Sin registro hoy",
            "tap_to_record" to "Toca para registrar tu ánimo",
            "streak_great" to "¡Genial! Racha de %d días",
            "streak_none" to "Aún sin registro hoy",
            "history" to "Historial",
            "tab_home" to "Inicio",
            "tab_diary" to "Diario",
            "diary_title" to "Mi diario",
            "diary_new" to "Nueva entrada",
            "diary_edit" to "Editar entrada",
            "diary_hint" to "¿Qué pasó hoy?",
            "diary_empty" to "Aún no hay entradas: escribe la primera ✨",
            "diary_count" to "%d entradas",
            "diary_recent7" to "%d en los últimos 7 días",
            "diary_delete_confirm" to "¿Eliminar esta entrada?",
            "total_count" to "%d registros",
            "empty_hint" to "Sin registros. Toca ＋ para empezar",
            "record_mood" to "Registrar ánimo",
            "edit_record" to "Editar registro",
            "date_label" to "Fecha",
            "today" to "Hoy",
            "mood_prompt" to "¿Cómo te sientes?",
            "intensity_label" to "Intensidad",
            "note_hint" to "¿Qué pasó? (opcional)",
            "backfill_hint" to "Se registrará el %s",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "stats_title" to "Estadísticas",
            "stats_month_count" to "%d días este mes",
            "stats_empty" to "Sin registros este mes 🌱",
            "close" to "Cerrar",
            "settings" to "Ajustes",
            "ios_style" to "Estilo iOS 27 Glass",
            "ios_current" to "Actual: iOS 27 Glass",
            "material_current" to "Actual: Material clásico",
            "export_csv" to "Exportar datos (CSV)",
            "export_desc" to "%d registros, comparte por WeChat/TikTok",
            "clear_all" to "Borrar todos los datos",
            "clear_desc" to "No se puede deshacer",
            "about" to "Acerca de",
            "version" to "Mood Diary v 1.1.0-alpha01",
            "about_desc" to "Registra cada día, tu asistente interior.",
            "author" to "Desarrollado por Wenbin Wei  " +
                    "Copyright © 2026 Cmpss. All Rights Reserved.",
            "clear_confirm" to "¿Borrar todos los datos?",
            "clear_confirm_desc" to "Se eliminarán %d registros permanentemente.",
            "clear_yes" to "Sí, borrar",
            "clear_no" to "Espera, déjame pensar",
            "menu_stats" to "Estadísticas",
            "menu_card_style" to "Estilo de tarjeta",
            "menu_backfill" to "Registro retroactivo",
            "menu_settings" to "Ajustes",
            "menu_more" to "Más",
            "share_title" to "Compartir ánimo",
            "save_album" to "Guardar en álbum",
            "share" to "Compartir",
            "saved_to_album" to "Guardado en álbum",
            "save_failed" to "Error al guardar",
            "share_to" to "Compartir con",
            "card_style_title" to "Estilo de tarjeta",
            "section_appearance" to "Apariencia",
            "label_background" to "Fondo",
            "bg_glass" to "Cristal",
            "bg_plain" to "Sólido",
            "bg_gradient" to "Degradado",
            "bg_photo" to "Foto",
            "select_photo" to "Seleccionar foto personalizada",
            "change_photo" to "Cambiar foto",
            "photo_selected" to "Seleccionada · toca para cambiar",
            "clear_photo" to "Borrar",
            "show_emoji" to "Mostrar emoji",
            "show_date" to "Mostrar fecha",
            "show_stars" to "Mostrar estrellas",
            "label_radius" to "Radio",
            "section_share_card" to "Tarjeta compartida",
            "use_custom_photo" to "Usar foto personalizada de fondo",
            "label_template" to "Plantilla",
            "watermark" to "Mostrar marca de agua",
            "done" to "Hecho",
            "language" to "Idioma",
            "mood_happy" to "Feliz",
            "mood_calm" to "Tranquilo",
            "mood_sad" to "Triste",
            "mood_angry" to "Enojado",
            "mood_anxious" to "Ansioso",
            "custom_toggle" to "Icono y nombre personalizado",
            "custom_toggle_collapse" to "Contraer",
            "custom_scope_hint" to "Se aplica a todos los registros \"%s\"",
            "custom_icon_label" to "Icono",
            "custom_name_label" to "Nombre",
            "custom_preview" to "Vista previa",
            "save_global" to "Guardar global",
            "clear" to "Borrar",
            "watermark_text" to "— Mood Diary —",
            "watermark_national" to "— Mood Diary · Día Nacional —",
            "national_title" to "Feliz Día Nacional",
            "tpl_national" to "Nacional",
            "tpl_classic" to "Clásico",
            "tpl_minimal" to "Minimal",
            "tpl_paper" to "Revista",
            "tpl_dark" to "Oscuro",
            "tpl_note" to "Nota",
            "custom_mood_new" to "Nuevo ánimo",
            "custom_mood_edit" to "Editar ánimo",
            "custom_mood_delete" to "Eliminar ánimo",
            "custom_mood_emoji" to "Icono",
            "custom_mood_label" to "Nombre",
            "custom_mood_add" to "Añadir",
            "custom_mood_empty" to "Sin ánimos personalizados",
            "custom_mood_hint" to "Introduce emoji y nombre",
            "custom_mood_delete_confirm" to "¿Eliminar este ánimo?",
            "custom_mood_delete_desc" to "Los registros existentes siguen visibles",
            "delete" to "Eliminar",
            "confirm" to "Confirmar"
        )
    )
}